#!/bin/bash
# Compile Script
# Ripunk16 & hendramanu
# YouTube Ripunk16
# Github : https://github.com/ripunk
# Github : https://github.com/hendramanu

clear
AWAL=$(pwd)
a="cd .."
function check_config() {
	if [ -e output/.config ] || [ -e .config ]; then
		echo "Current config detected! Skipping..."
		BARU=NGGAK
	else
		BARU=IYA
		$a
		rm -r output > /dev/null 2>&1
		mkdir output
		make clean > /dev/null 2>&1
		make mrproper > /dev/null 2>&1
	fi
}

# Variable
EX="export CROSS_COMPILE="
PROC=`grep processor /proc/cpuinfo|wc -l`
defcon="$a ls arch/arm64/configs"

if [ "$BARU" == "NGGAK" ]; then
    C_D="make O=output"
	C_O="make O=output -j$PROC"
	COM="make -j$PROC"
	CM_O=echo "Old config! Skipping menuconfig"
	CM=echo "Old config! Skipping menuconfig"
else
	CM_O="make O=output menuconfig"
	CM="make menuconfig"
	COM="make -j$PROC"
	C_O="make O=output -j$PROC"
	C_D="make O=output"
fi

# Colors
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
purple="\033[0;35m"
cyan="\033[0;36m"
cafe="\033[0;33m"
fiuscha="\033[0;35m"
blue="\033[1;34m"
transparent="\e[0m"
#########

# Add repo
function add_repo(){
if grep -Fxq "deb http://ports.ubuntu.com/ubuntu-ports xenial main restricted universe multiverse" /etc/apt/sources.list; then
	echo "Repo already added!"
else
	echo " Adding Ubuntu 16.04 Xenial And 18.04 Bionic Repository"
sleep 2
echo "deb http://ports.ubuntu.com/ubuntu-ports bionic main restricted universe multiverse" >>  /etc/apt/sources.list
echo "deb http://ports.ubuntu.com/ubuntu-ports bionic-security main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb http://ports.ubuntu.com/ubuntu-ports bionic-updates main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb http://ports.ubuntu.com/ubuntu-ports bionic-backports main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb http://ports.ubuntu.com/ubuntu-ports xenial main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb http://ports.ubuntu.com/ubuntu-ports xenial-security main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb http://ports.ubuntu.com/ubuntu-ports xenial-updates main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb http://ports.ubuntu.com/ubuntu-ports xenial-backports main restricted universe multiverse" >> /etc/apt/sources.list
gpg --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32 > /dev/null 2>&1
sleep 3
gpg -a --export 3B4FE6ACC0B21F32 | sudo apt-key add - > /dev/null 2>&1
sleep 3
fi
}


# Install gcc-4.9
function install_gcc-4.9(){
if ! type gcc-4.9 2>/dev/null; then
	echo "Installing GCC 4.9..."
	add_repo
	apt update
 	apt install bc bison build-essential ccache curl flex git gnupg gperf imagemagick liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev -y
	apt install gcc-4.9 g++-4.9 -y
	update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 30 > /dev/null 2>&1
	update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 30 > /dev/null 2>&1
 	sleep 0.5
	clear
else
	echo "GCC already Installed... Skipping"
	sleep 0.5
	clear
fi

}

#install gcc-5
function install_gcc-5(){
if ! type gcc-5 2>/dev/null; then
	             echo "Installing GCC..."
	   add_repo
           apt update
           apt install bc bison build-essential ccache curl flex git gnupg gperf imagemagick liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
           apt install gcc-5 g++-5
           update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 > /dev/null 2>&1
           update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 60 > /dev/null 2>&1
                     sleep 0.5
                     clear
	else
                     echo "GCC already Installed..."
		     sleep 0.6
                     clear
	fi
}

#compile
function compile_univ(){
$EX
if [ $BARU == NGGAK ]; then
	echo "Not make defconfig due to old config"
	$C_O
else
echo "Choose Config "
echo ""
ls arch/arm64/configs
if [ -e arch/arm64/configs/vendor ]; then
	echo "In vendor : "
	ls arch/arm64/configs/vendor
echo ""
echo " If your defconfig is in vendor folder, please add vendor/ in your input"
echo " Example : vendor/nethunter_defconfig"
fi
echo ""
read -p "[Defconfig] : " conf;
$C_D $conf
sleep 1
$CM_O
sleep 1
$C_O
dc=$?
if [ $dc != 0 ]; then
$C_O
fi
fi
}

function compile_samsung(){
$EX
if [ $BARU == NGGAK ]; then
	echo "Not make defconfig due to old config!"
	$COM
else
echo "Choose Config "
echo ""
ls arch/arm64/configs
echo ""
read -p "[Defconfig] : " conf;
$COM $conf
sleep 1
$CM
sleep 1
$COM
fi
}

function device() {
clear
echo "Choose your device :"
echo -e ""$red["$yellow"1"$red"] "$green"Samsung""$transparent"
""$red["$yellow"2"$red"] "$green"Xiaomi and other""$transparent"
echo ""
echo -n "[Device] : "
read device
case $device in
1)
compile_samsung

esac

case $device in
2)
compile_univ

esac

}

function banner() {
echo -e $fiuscha " X --------------- X " $transparent
echo -e $fiuscha "  ______ ___   ___   " $transparent
echo -e $blue    " |  ____/ _ \ / _ \  " $transparent
echo -e $red     " | |__ | (_) | (_) | " $transparent
echo -e $purple  " |  __| \__  |\__  | " $transparent
echo -e $yellow  " | |____  / /   / /  " $transparent
echo -e $green   " |______|/_/   /_/   " $transparent
echo  ""
echo  -e $fiuscha" X --------------- X " $transparent
echo -e $cyan " S C R I P T "
echo ""
echo "| https://github.com/nethunter-indo/compile             |"
echo "| Author 1 : ripunk (https://youtube.com/Ripunk16)      |"
echo "| Author 2 : hendramanu (https://github.com/hendramanu) |"
echo "" ""
}
#menu
function menu(){
echo -e ""
echo -e ""$red"["$yellow"1"$red"]"$green"Compile"
echo -e ""$red"["$yellow"2"$red"]"$green"Install GCC 4.9 "$red"recommended ""$tranparent"
echo -e ""$red"["$yellow"3"$red"]"$green"Install GCC 5.0 "
echo -e ""$red"["$yellow"4"$red"]"$green"Clang "$red"(NOT AVAILABLE YET)""$transparent"
echo -e ""$red"["$yellow"5"$red"]"$green"Exit""$transparent"
echo -e ""
echo -n "[root@E99 | hendramanu] : "
read pil
case $pil in
1)
device
esac

case $pil in
2)
install_gcc-4.9
menu
esac

case $pil in
3)
install_gcc-5
menu
esac

case $pil in
4)

esac

case $pil in
5)
sleep 0.5
exit

esac

case $pil in
*)
echo "Invalid!"
sleep 1
menu

esac
}

banner
check_config
menu
